const advices = [
    "Acredite em si mesmo e vá em frente.",
    "Não tenha medo de recomeçar.",
    "Você é mais forte do que pensa.",
    "Respire fundo e confie no processo.",
    "Todo dia é uma nova chance.",
    "Seja gentil consigo mesmo.",
    "O erro é parte do aprendizado.",
    "Mantenha o foco no que importa.",
    "Permita-se descansar.",
    "Você está no caminho certo.",
    "Acredite no seu potencial e não desista.",
    "Faça o seu melhor, mesmo nos dias difíceis.",
    "Aprenda com cada queda.",
    "O silêncio também é uma resposta.",
    "Desacelere. Tudo tem seu tempo.",
    "A coragem vem depois da decisão.",
    "Abrace suas imperfeições.",
    "Você não precisa agradar a todos.",
    "Pequenos passos também te levam longe.",
    "Seja constante, não perfeito.",
    "O agora é tudo o que você tem.",
    "Confie no que você sente.",
    "Nada muda se você não mudar.",
    "Você não está sozinho.",
    "A vida também é feita de pausas.",
    "O cansaço não define sua capacidade.",
    "O medo é só um sinal de que você se importa.",
    "Você pode recomeçar quantas vezes quiser.",
    "Não se compare com ninguém.",
    "Valorize suas conquistas, mesmo as pequenas.",
    "A gentileza transforma tudo.",
    "Não tenha pressa, tenha direção.",
    "Permita-se sentir sem culpa.",
    "O aprendizado vem da prática.",
    "Ouça mais o seu coração.",
    "Ser forte também é pedir ajuda.",
    "Sua jornada é só sua.",
    "Erre tentando, nunca por medo.",
    "O que é seu encontrará o caminho.",
    "O hoje é a chance de fazer diferente.",
    "Você é capaz de lidar com isso.",
    "Seja a sua melhor companhia.",
    "O que te faz bem deve caber na sua rotina.",
    "Não apresse o que precisa de tempo.",
    "Você é suficiente como é.",
    "Respirar fundo também é uma resposta.",
    "Sua mente precisa de descanso tanto quanto seu corpo.",
    "A gratidão muda o olhar.",
    "Não existe caminho certo, existe o seu.",
    "Desistir de algo que machuca é sabedoria.",
    "A vida acontece fora da zona de conforto.",
    "Você está aprendendo, e isso basta.",
    "Ser leve é mais importante do que ser perfeito.",
    "Não se cobre tanto. Você está indo bem.",
    "Acredite no valor das pequenas atitudes.",
    "A mudança começa por dentro.",
    "Você não precisa entender tudo agora.",
    "Dar um passo já é progresso.",
    "O importante é continuar.",
    "Você pode. Sempre pôde.",
    "Escolha o que te aproxima da paz.",
    "Você merece tudo de bom que deseja.",
    "Seja gentil consigo mesmo sempre.",
    "O esforço vale mais que a sorte.",
    "Seus sonhos são importantes.",
    "Faça o que te faz feliz.",
    "Confie no seu caminho.",
    "Aprenda com os erros.",
    "Cada dia é uma nova chance.",
    "Valorize quem está ao seu lado.",
    "Seja grato pelas pequenas coisas.",
    "O amor próprio transforma vidas.",
    "Você é capaz de superar desafios.",
    "Cultive pensamentos positivos.",
    "Tenha paciência com o processo.",
    "Faça o bem sem esperar retorno.",
    "Sua saúde é prioridade.",
    "Não desista antes de tentar.",
    "Cresça um pouco a cada dia.",
    "A vida é feita de escolhas.",
    "Seja a mudança que deseja ver.",
    "Valorize seu tempo e energia.",
    "O sorriso é um ato de coragem.",
    "O melhor ainda está por vir.",
    "Confiança é a base de tudo.",
    "Seja fiel aos seus valores.",
    "A felicidade mora nas coisas simples.",
    "Respeite seu próprio ritmo.",
    "Acredite na força dos seus sonhos.",
    "Você é mais forte do que imagina.",
    "Olhe para frente com esperança.",
    "Aprender é um presente diário.",
    "Amar-se é um ato revolucionário.",
    "A persistência quebra barreiras.",
    "A vida é feita de momentos.",
    "Tenha coragem para ser você.",
    "Cada desafio traz um aprendizado.",
    "O respeito começa em você.",
    "Não tenha medo de pedir ajuda.",
    "Você merece paz e alegria.",
    "Celebre suas pequenas conquistas.",
    "A gratidão transforma o coração.",
    "Permita-se sentir e viver.",
    "O amor cura e fortalece.",
    "Sonhe alto, comece pequeno.",
    "A determinação vence o medo.",
    "Seja luz onde estiver.",
    "O tempo revela o que importa.",
    "Seja sincero consigo mesmo.",
    "Ouça mais do que fala.",
    "Invista em sua felicidade.",
    "Viva o presente com intensidade.",
    "Você é responsável pelo seu sorriso.",
    "Faça a diferença todos os dias.",
    "Encontre beleza nas dificuldades.",
    "Coragem é agir mesmo com medo.",
    "Esteja aberto para mudanças.",
    "Seja grato pelos desafios.",
    "Você é único e especial.",
    "Permita-se aprender sempre.",
    "Não se compare aos outros.",
    "Cuide da sua mente e corpo.",
    "Aprenda a perdoar-se.",
    "Busque equilíbrio na vida.",
    "Seja paciente com os outros.",
    "Peça o que você merece.",
    "Valorize seus talentos.",
    "Aprenda a dizer não.",
    "Seja humilde para crescer.",
    "Confie no seu tempo.",
    "Você pode transformar sua história.",
    "Não tenha pressa para os resultados.",
    "Crie sua própria felicidade.",
    "Escolha a paz em cada situação.",
    "Seja grato pelo que tem.",
    "Você é maior que seus medos.",
    "Aprenda a escutar seu coração.",
    "Seja gentil com quem cruza seu caminho.",
    "Transforme dificuldades em aprendizados.",
    "Seja curioso e busque conhecimento.",
    "O respeito é o começo do amor.",
    "Confie no processo da vida.",
    "Viva com propósito e paixão.",
    "A coragem nasce da ação.",
    "Faça o que te traz paz.",
    "Não desista dos seus valores.",
    "Seja luz em tempos escuros.",
    "Cada dia é uma nova oportunidade.",
    "Tenha fé no seu potencial.",
    "Sorria mesmo sem motivo.",
    "Construa sua própria felicidade.",
    "Ame sem medidas.",
    "Cuide de quem você ama.",
    "Seja a melhor versão de si mesmo.",
    "Você é dono do seu destino."
];

function mostrarConselheiro() {
    document.getElementById('welcomeScreen').classList.remove('active');
    document.getElementById('adviceScreen').classList.add('active');
}

function voltarInicio() {
    document.getElementById('adviceScreen').classList.remove('active');
    document.getElementById('welcomeScreen').classList.add('active');
}

function showAdvice() {
    const randomIndex = Math.floor(Math.random() * advices.length);
    document.getElementById('advice').innerText = advices[randomIndex];
}
